### ISSUE TITLE
After i refresh, the comparison values i set are not shown.

### ISSUE THREAD

**Issue by my2dream** [AutohomeCorp/graph-compare-panel#1]
After i refresh, the comparison values i set are not shown.

before :
![init](https://user-images.githubusercontent.com/41362017/50744525-416b6700-1267-11e9-80bf-95dfa4bb73fa.PNG)

after_refresh:
![after_refresh](https://user-images.githubusercontent.com/41362017/50744528-4cbe9280-1267-11e9-8394-0067d91d5c7b.PNG)

grafana version: 
![version](https://user-images.githubusercontent.com/41362017/50744546-84c5d580-1267-11e9-997f-fd52e4cc3faa.PNG)

data source: influxDB

**Comment by victr** [comment]
same here, after updating to v5.4.3

**Comment by nfw999** [comment]
Resolve compatibility issues after update

**Comment by poonab** [comment]
This issue appears to be still present?

**Comment by my2dream** [comment]
after update, it resolved, thanks.
