### ISSUE TITLE
How to use variable as timeshift?

### ISSUE THREAD

**Issue by hhtHW** [AutohomeCorp/graph-compare-panel#10]

**Comment by hhtHW** [comment]
![image](https://user-images.githubusercontent.com/8456861/66267783-24041180-e868-11e9-800b-4a28af9041ec.png)

when i use a variable in time shifit, it seems that the graph fail to show

**Comment by nfw999** [comment]
Thanks for your advice ，We added this feature to the last version.

**Comment by hhtHW** [comment]
Greate Thanks! It's very useful.
