### ISSUE TITLE
Compare query signed by grafanalabs

### ISSUE THREAD

**Issue by RidolfoFabien** [AutohomeCorp/graph-compare-panel#19]
Hello,

I'm so happy to use this plugin in my grafana.

I was wondering if is it possible for you to sign your plugin with grafanalabs because it seems that in grafana 8 all unsigned plugins won't work anymore.

Thanks for you answers,
Regards,

**Comment by nfw999** [comment]
This plugin is no longer maintained, we switched to using [autohome-compareQueries-datasource](https://github.com/AutohomeCorp/autohome-compareQueries-datasource) instead，the new plugin is a datasource plugin with better compatibility

**Comment by RidolfoFabien** [comment]
Thank you, i'll switch to the datasource plugin :)
