### ISSUE TITLE
Color picker does not work

### ISSUE THREAD

**Issue by victr** [AutohomeCorp/graph-compare-panel#2]
When I click on a colored line in the legend I can choose the color for the series. But for the graph compare panel the color picker is empty and does not have any options. 
ER: ![image](https://user-images.githubusercontent.com/1419684/51974734-e51fef80-2480-11e9-8dba-d4416c969f5a.png)
AR: ![image](https://user-images.githubusercontent.com/1419684/51974754-efda8480-2480-11e9-8405-dcd5c134e6af.png)
The same happens in the series override.
![image](https://user-images.githubusercontent.com/1419684/51974799-0bde2600-2481-11e9-9d83-4ed3a0a5f1e2.png)

**Comment by nfw999** [comment]
We resolve this problem in branch 'graph-compare-panel-for-grafana-5.4.x'
