### ISSUE TITLE
Adding Override relative time

### ISSUE THREAD

**Issue by glsf91** [AutohomeCorp/graph-compare-panel#3]
Thanks for this great panel. Just what I was looking for.

But it should be nice if it is also possible to add the "Override relative time" which is in the standard graph panel. 
For example, I want to show a graph for the last 7 days in depended of the time picker. Then also add for compare the previous 1 or 2 weeks which your panel can do.
So if the timepicker is Today I want to see the "main" graph from 7days ago until now. And then also as compare a graph from 14-7 days ago. 

For  "Override relative time" I prefer all possibilities which are there in the standard panel. Like "7d/d" etc.

**Comment by nfw999** [comment]
Thanks for your advice ，We added "Override relative time" to the new version.
