### ISSUE TITLE
When the time-shift is used, the Snapshot displays no data and legends are messed up

### ISSUE THREAD

**Issue by ywang0701** [AutohomeCorp/graph-compare-panel#5]
This is a great plugin and solves the problem I am addressing. Thanks!  The plugin has issue with Snapshot. Steps to repro:

1. Display data in Graph Panel
2. Create a Time shift  
3. Share Dashboard -> Snap-shot -> Local Snapshot
4. The generated snapshot does not display any data and the snapshot has duplicated-legends
 
![image](https://user-images.githubusercontent.com/7120555/55501586-9537e300-55ff-11e9-9491-466477d39ba0.png)

**Comment by nfw999** [comment]
Fix this bug in the latest  version
