### ISSUE TITLE
Branch 'master' can work on Grafana versions 6.0

### ISSUE THREAD

**Issue by hadesLiu** [AutohomeCorp/graph-compare-panel#6]
This is a great plugin and solves the problem I am addressing. Thanks! 
Grafana is upgraded in versions 6.0，I hope this plugin can work on  Grafana versions 6.0 in the future.

**Comment by glsf91** [comment]
Do you have plans to migrate this plugin to Grafana 6.x?

**Comment by Bursade** [comment]
Is there any update to make this compatible with Grafana 6.1?

**Comment by sanutey** [comment]
The 6.x version has changed a lot. We need some time to adapt, or we have to redesign the solution, and it has been a bit busy recently, so the new version of the plugin still needs to wait for a while.

**Comment by phreakadelle** [comment]
Works for me with 6.4.3

**Comment by nfw999** [comment]
This plugin is no longer maintained, we switched to using [grafana-compare-queries](https://github.com/AutohomeCorp/grafana-compare-queries) instead.

Also works with 6.x
